[package]
name = "coremidi"
version = "0.2.0"
authors = ["Christian Perez-Llamas"]
description = "CoreMIDI library for Rust"
license = "MIT"
homepage = "https://github.com/chris-zen/coremidi"
repository = "https://github.com/chris-zen/coremidi"
documentation = "https://chris-zen.github.io/coremidi/coremidi/"
readme = "README.md"
keywords = ["CoreMIDI", "MIDI", "OSX", "music"]


[dependencies]
core-foundation-sys = "0.2"
core-foundation = "0.2"
coremidi-sys = "2.0"
time = "0.1"
